language: node_js
node_js:
  - 16.9

services:
  - docker

before_install:
  - docker build -t "$DOCKER_IMAGE_NAME":latest .
  
script:
  - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE_NAME":latest